### ISSUE TITLE
What's the point of fusion?

### ISSUE THREAD

**Issue by stdoo** [soujanyaporia/multimodal-sentiment-analysis#11]
Hi, I have tried some of the commands, and the results are:

```
Command1：
python run.py --unimodal True --fusion True --attention_2 True
Results：
Best epoch: 40
Best test accuracy: 0.7593085169792175
Best epoch loss: 22
Best test accuracy when loss is least: 0.7433510422706604



Command2：
python run.py --unimodal False --fusion True --attention_2 True
Results：
Best epoch: 33
Best test accuracy: 0.7619680762290955
Best epoch loss: 21
Best test accuracy when loss is least: 0.7380319237709045



Command3：
python run.py --unimodal True --fusion False
Results：
Best epoch: 12
Best test accuracy: 0.769946813583374
Best epoch loss: 11
Best test accuracy when loss is least: 0.7659574747085571



Command4:
python run.py --unimodal True --fusion True
Results:
Best epoch: 13
Best test accuracy: 0.7659574747085571
Best epoch loss: 12
Best test accuracy when loss is least: 0.7606382966041565



Command5:
python run.py --unimodal False --fusion True
Results:
Best epoch: 14
Best test accuracy: 0.769946813583374
Best epoch loss: 13
Best test accuracy when loss is least: 0.7686170339584351



Command6:
python run.py --unimodal False --fusion False
Results:
Best epoch: 12
Best test accuracy: 0.7659574747085571
Best epoch loss: 11
Best test accuracy when loss is least: 0.7606382966041565
```
Firstly, I think Command1 will be the best, but the result is not. The best result comes from Command3 and Command5(both without attention_2), so what's the point of doing attention_2? Besides, why do you use fscore instead of accuracy in your paper? 

Secondly, the best accuracy of Command3(without fusion) is better than Command 4, so what's the point of fusion?

**Comment by stdoo** [comment]
@soujanyaporia I don't think it's because of --unimodal True, I can get the best result with Command 3, which is the same accuracy with Command 5.

**Comment by soujanyaporia** [comment]
What do you mean? I strongly recommend to use the pickle files provided in this repo. If you want to train the unimodals then please do optimise the networks to get the best result. Using the existing pickle files, anyone can get accuracy of 80%

**Comment by Eurus-Holmes** [comment]
@stdoo Actually, I also have the same question with you...
