### ISSUE TITLE
code for dimension equalization

### ISSUE THREAD

**Issue by marcostx** [soujanyaporia/multimodal-sentiment-analysis#6]
Hi, 
Could you share the script used to perform the dimension equalization ( d=300 ), cited on paper (Multi-level Multiple Attentions for Contextual Multimodal Sentiment Analysis) for multimodal fusion experiment ?

**Comment by marcostx** [comment]
1.6.0

**Comment by soujanyaporia** [comment]
It is already there in the code. Please check the attention function.
